export const NOTES_LIST_REQUEST: string = "NOTES_LIST_REQUEST";
export const NOTES_LIST_SUCCESS: string = "NOTES_LIST_SUCCESS";
export const NOTES_LIST_FAIL: string = "NOTES_LIST_FAIL";

export const NOTES_CREATE_REQUEST: string = "NOTES_CREATE_REQUEST";
export const NOTES_CREATE_SUCCESS: string = "NOTES_CREATE_SUCCESS";
export const NOTES_CREATE_FAIL: string = "NOTES_CREATE_FAIL";

export const NOTES_UPDATE_REQUEST: string = "NOTES_UPDATE_REQUEST";
export const NOTES_UPDATE_SUCCESS: string = "NOTES_UPDATE_SUCCESS";
export const NOTES_UPDATE_FAIL: string = "NOTES_UPDATE_FAIL";

export const NOTES_DELETE_REQUEST: string = "NOTES_DELETE_REQUEST";
export const NOTES_DELETE_SUCCESS: string = "NOTES_DELETE_SUCCESS";
export const NOTES_DELETE_FAIL: string = "NOTES_DELETE_FAIL";
